data: "data.json"

output: "build/"

src:
  templates: 
    dir: "templates/"
    partials: "templates/partials/"

  static:
    dir: "static/"
    fonts: "static/fonts/"
    styles: "styles/"
    images: "."

mustache_ext: "mustache"
partial_ext: "mustache"
resume_projects_limit: 4
git-publish: false