<header class="header">
    <div class="title"><a href="index.html">{{name}}</a></div>
    <nav>
        <ul class="menu">
            <li class="about {{#projects}}selected{{/projects}}"><a href="index.html">About me</a></li>
            <li class="resume {{#projects}}selected{{/projects}}"><a href="resume.html">Resumé</a></li>
            <li class="projects {{#projects}}selected{{/projects}}"><a href="projects.html">Projects</a></li>
        </ul>
    </nav>
</header>


